routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Non protected/public routes
Route::get('/', 'WelcomeController@index');
Route::get('pdashboard', 'DashboardController@index');
Route::get('pdashboard/detail', 'DashboardController@detail');
Route::get('pdashboard/detail_nrw', 'DashboardController@detail_nrw');
// Login Logout
Route::get('login', 'Auth\LoginController@showLoginForm');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout');
// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
// Regisration
Route::get('register', 'Auth\RegisterController@showRegistrationForm');
Route::post('register', 'Auth\RegisterController@register');
Route::get('activate', 'Auth\ActivateController@showActivate');
Route::get('activate/send-token', 'Auth\ActivateController@sendToken');
Route::get('activate/token/{token}', 'Auth\ActivateController@activate');

// HARUS login / Authenticated Routes
Route::group(['middleware' => ['auth', 'active']], function () {
    // User stuff
    Route::get('/users/switch-back', 'Admin\UserController@switchUserBack');
    Route::group(['prefix' => 'user', 'namespace' => 'User'], function () {
        Route::get('settings', 'SettingsController@settings');
        Route::post('settings', 'SettingsController@update');
        Route::post('editmeta/{id}', 'SettingsController@updatemeta');
        Route::get('password', 'PasswordController@password');
        Route::post('password', 'PasswordController@update');
    });
    // Dashboard
    Route::get('/dashboard', 'PagesController@dashboard');

    // Team
    Route::get('team/{name}', 'TeamController@showByName');
    Route::resource('teams', 'TeamController', ['except' => ['show']]);
    Route::post('teams/search', 'TeamController@search');
    Route::post('teams/{id}/invite', 'TeamController@inviteMember');
    Route::get('teams/{id}/remove/{userId}', 'TeamController@removeMember');


    // HARUS login, HARUS admin atau member
    Route::group(['middleware' => 'roles:admin|member'], function () {
        Route::resource('contents', 'ContentsController');
        Route::post('contents/search', [
            'as' => 'contents.search',
            'uses' => 'ContentsController@search'
        ]);
    });

    // HARUS login, HARUS admin
    Route::group(['middleware' => 'roles:admin'], function () {
      // Organization & References
      Route::resource('companies', 'CompaniesController');
      Route::post('companies/search', [
          'as' => 'companies.search',
          'uses' => 'CompaniesController@search'
      ]);

      // CMS
      Route::resource('topics', 'TopicsController');
      Route::post('topics/search', [
          'as' => 'topics.search',
          'uses' => 'TopicsController@search'
      ]);
      Route::resource('categories', 'CategoriesController');
      Route::post('categories/search', [
          'as' => 'categories.search',
          'uses' => 'CategoriesController@search'
      ]);
      Route::resource('offlinewriters', 'OfflineWritersController');
      Route::post('offlinewriters/search', [
          'as' => 'offlinewriters.search',
          'uses' => 'OfflineWritersController@search'
      ]);
      Route::resource('comments', 'CommentsController');
      Route::post('comments/search', [
          'as' => 'comments.search',
          'uses' => 'CommentsController@search'
      ]);
      // Log System
      Route::resource('logsystems', 'LogsystemsController');
      Route::post('logsystems/search', [
          'as' => 'logsystems.search',
          'uses' => 'LogsystemsController@search'
      ]);
      // Spams
      Route::resource('spams', 'SpamsController');
      Route::post('spams/search', [
          'as' => 'spams.search',
          'uses' => 'SpamsController@search'
      ]);

      // Dma
      Route::resource('dmas', 'DmasController');
      Route::post('dmas/search', [
      'as' => 'dmas.search',
      'uses' => 'DmasController@search'
      ]);
      Route::post('dmas/assign', [
      'as' => 'dmas.assign',
      'uses' => 'DmasController@assign'
      ]);

      // Zona
      Route::resource('zonas', 'ZonasController');
      Route::post('zonas/search', [
          'as' => 'zonas.search',
          'uses' => 'ZonasController@search'
      ]);

      // Brand
      Route::resource('brands', 'BrandsController');
      Route::post('brands/search', [
          'as' => 'brands.search',
          'uses' => 'BrandsController@search'
      ]);
      // Location
      Route::resource('locations', 'LocationsController');
      Route::post('locations/search', [
          'as' => 'locations.search',
          'uses' => 'LocationsController@search'
      ]);

      // Station
      Route::resource('stations', 'StationsController');
      Route::post('stations/search', [
          'as' => 'stations.search',
          'uses' => 'StationsController@search'
      ]);

      // Device
      Route::resource('devices', 'DevicesController');
      Route::post('devices/search', [
          'as' => 'devices.search',
          'uses' => 'DevicesController@search'
      ]);

      // Grafik & Statistik
      Route::get('waterbalance', [
          'as' => 'nrws.waterbalance',
          'uses' => 'NrwsController@waterbalance'
      ]);
      Route::get('chartmeasurement', [
          'as' => 'nrws.chartmeasurement',
          'uses' => 'NrwsController@chartmeasurement'
      ]);


    });

    // HARUS login, HARUS admin dan controllernya HARUS di /admin
    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
        // User
        Route::resource('users', 'UserController', ['except' => ['create', 'show']]);
        Route::post('users/search', 'UserController@search');
        Route::get('users/search', 'UserController@index');
        Route::get('users/invite', 'UserController@getInvite');
        Route::get('users/switch/{id}', 'UserController@switchToUser');
        Route::post('users/invite', 'UserController@postInvite');
        // Roles
        Route::resource('roles', 'RoleController', ['except' => ['show']]);
        Route::post('roles/search', 'RoleController@search');
        Route::get('roles/search', 'RoleController@index');
    });
});

app/Models/Station.php
<?php
namespace App\Models; 
use Illuminate\Database\Eloquent\Model;
use App\Models\Device;
use App\Models\Spam;
use App\Models\Zona;
use App\Models\Dma;
//nambah model brand dan location
use DB;

class Station extends Model
{
    public $table = "stations";

    public $primaryKey = "id";

    public $timestamps = true;

    public $fillable = [
        'id',
        'brand_id',
        'location_id',
        'name',
        'instalation_date',
        'lat',
        'long',
        'v_spam_kode_id',
        'kode',
        'spam_id',
        'zona_id',
        'dma_id',
        'kode',
        'chart_url',
        'data_url',

    ];

    public static $rules = [
        // create rules
    ];

    // Station 
    public function spam()
    {
        return $this->belongsTo(Spam::class, 'spam_id');
    }

    public function zona()
    {
        return $this->belongsTo(Zona::class, 'zona_id');
    }
    public function dma()
    {
        return $this->belongsTo(Dma::class, 'dma_id');
    }
    public function devices()
    {
        return $this->hasMany(Device::class, 'brand_id');
    }

    public function nama_kode()
    {
        return $this->select('name', DB::raw("CONCAT(`kode`, ' - ', `name`) AS name"),'id')->get();
    }



}

app/Http/Controllers/StationsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\StationService;
use App\Http\Requests\StationCreateRequest;
use App\Http\Requests\StationUpdateRequest;
use Mapper;

class StationsController extends Controller
{
    public function __construct(StationService $stationService)
    {
        $this->service = $stationService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $stations = $this->service->paginated();
        return view('stations.index')->with('stations', $stations);
    }

    /**
     * Display a listing of the resource searched.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $stations = $this->service->search($request->search);
        return view('stations.index')->with('stations', $stations);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       Mapper::map(-6.9809279,107.486755, [
        'draggable' => true,
        'eventDragEnd' =>
        'document.getElementById("Lat").value=event.latLng.lat();
        document.getElementById("Long").value=event.latLng.lng();'
    ]);
       return view('stations.create');
   }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\StationCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StationCreateRequest $request)
    {
        $result = $this->service->create($request->except('_token'));

        if ($result) {
            return redirect(route('stations.index'))->with('message', 'Successfully created');
            //return redirect(route('stations.edit', ['id' => $result->id]))->with('message', 'Successfully created');
        }

        return redirect(route('stations.index'))->with('message', 'Failed to create');
    }

    /**
     * Display the station.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $station = $this->service->find($id);
        return view('stations.show')->with('station', $station);
    }

    /**
     * Show the form for editing the station.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $station = $this->service->find($id);
        if ($station->lat != null) {
          Mapper::map($station->lat,$station->long, [
            'draggable' => true,
            'eventDragEnd' =>
            'document.getElementById("Lat").value=event.latLng.lat();
            document.getElementById("Long").value=event.latLng.lng();'
        ]);
      } else  Mapper::map(-6.9809279,107.486755, [
        'draggable' => true,
        'eventDragEnd' =>
        'document.getElementById("Lat").value=event.latLng.lat();
        document.getElementById("Long").value=event.latLng.lng();'
    ]);
      return view('stations.edit')->with('station', $station);
  }

    /**
     * Update the stations in storage.
     *
     * @param  \Illuminate\Http\StationUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StationUpdateRequest $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
            //return back()->with('message', 'Successfully updated');
            return redirect(route('stations.index'))->with('message', 'Successfully updated');
        }

        return back()->with('message', 'Failed to update');
    }

    /**
     * Remove the stations from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->service->destroy($id);

        if ($result) {
            return redirect(route('stations.index'))->with('message', 'Successfully deleted');
        }

        return redirect(route('stations.index'))->with('message', 'Failed to delete');
    }
}

resources/views/stations/create.blade.php
@extends('dashboard')

@section('stylesheets')
<link rel="stylesheet" type="text/css" href="{{ url('css/jquery.datetimepicker.min.css') }}">
@stop

@section('javascript')
<script src="{{ url('js/jquery.datetimepicker.full.min.js') }}"></script>
<script>
    jQuery('#instalation_date').datetimepicker({
      format: 'Y-m-d H:i'
  });
</script>
@stop

@section('content')
<div class="row">
    <div class="col-md-12" style="background:#eee; border-radius:0 0 14px 14px; margin:4px;">
        <h1 class="pull-left"><span class="fa fa-tachometer"></span> Tambah Logger</h1>
    </div>
</div>
<div class="row raw-margin-top-24">
    <div class="col-md-6 raw-margin-bottom-24">
        {!! Form::open(['route' => 'stations.store']) !!}
        {!! csrf_field() !!}
        @form_maker_table("stations",[
            'id'=>['type'=>'hidden'],
            'brand_id'=>['alt_name'=>'Merek','type'=>'relationship','model' => 'App\Models\Brand','label'=>'name','value'=>'id'],
            'location_id'=>['alt_name'=>'Posisi','type'=>'relationship','model' => 'App\Models\Location','label'=>'name','value'=>'id'],        
            'name'=>['alt_name'=>'Nama'],
            'lat'=>['alt_name'=>'Latitude'],
            'long'=>['alt_name'=>'Longitude'],
            'spam_id'=>['alt_name'=>'Spam','type'=>'relationship',
            'model' => 'App\Models\Spam','label'=>'name','value'=>'id'],
            'zona_id'=>['alt_name'=>'Zona','type'=>'relationship',
            'model' => 'App\Models\Zona','label'=>'name','value'=>'id'],
            'dma_id'=>['alt_name'=>'Dma','type'=>'relationship',
            'model' => 'App\Models\Dma','label'=>'name','value'=>'id'],
            'v_spam_kode_id'=>['type'=>'hidden'],
            'kode'=>['alt_name'=>'Kode'],
            'chart_url'=>['alt_name'=>'Chart Url'],
            'data_url'=>['alt_name'=>'Data Url'],      
            ])

            <div class="form-group">
                <label class="control-label">Tanggal Instalasi</label>

                <input type="datetime-local" class="form-control" name="instalation_date" value="instalation_date" id="">
            </div>
            <div class="raw-margin-top-24">
                <a class="btn btn-default pull-left" href="{!! route('stations.index') !!}">Batal</a>
                <button class="btn btn-primary pull-right" type="submit">Buat</button>
            </div>

            {!! Form::close() !!}
        </div>
        <div class="col-md-6 raw-margin-bottom-24">
            <div class="form-group">
              <label class="control-label" for="avatar">
              Peta Area</label><br />(Drag marker untuk mengatur input koordinat)
              <div style="width: 300px; height: 300px; border:1px solid #ccc;">
                {!! Mapper::render() !!}
            </div>
        </div>
    </div>

</div>
</div>

@stop

resources/views/stations/edit.blade.php
@extends('dashboard')

@section('stylesheets')
<link rel="stylesheet" type="text/css" href="{{ url('css/jquery.datetimepicker.min.css') }}">
@stop

@section('javascript')
<script src="{{ url('js/jquery.datetimepicker.full.min.js') }}"></script>
<script>
  jQuery('#instalation_date').datetimepicker({
    format: 'Y-m-d H:i'
  });
  $('*[name=instalation_date]').val("{{$station->instalation_date}}");
</script>
@stop
@section('content')
<div class="row">
    <div class="col-md-12" style="background:#eee; border-radius:0 0 14px 14px; margin:4px;">
        <h1 class="pull-left"><span class="fa fa-tachometer"></span> Ubah Logger</h1>
    </div>
</div>
<div class="row">
  <div class="col-md-6 raw-margin-bottom-24">
    <div>
      {!! Form::model($station, ['route' => ['stations.update', $station->id], 'method' => 'patch']) !!}
      {!! csrf_field() !!}
      {!! method_field('PATCH') !!}
    <input type="hidden" name="id" value="{{ $station->id }}">
    <div class="raw-margin-top-24">
      @input_maker_label('Merek')
      @input_maker_create('devices', [
          'type' => 'relationship',
          'model' => 'App\Models\Brand',
          'label' => 'name',
          'value' => 'id'
          ],  $station)      
    </div>
    <div class="raw-margin-top-24">
      @input_maker_label('Posisi')
      @input_maker_create('location_id', ['type' => 'string'],$station)
    </div>
    <div class="raw-margin-top-24">
      @input_maker_label('Nama')
      @input_maker_create('name', ['type' => 'string'],$station)
    </div>
    <div class="raw-margin-top-24">
      @input_maker_label('Latitude')
      @input_maker_create('lat', ['type' => 'string'],$station)
    </div>
    <div class="raw-margin-top-24">
      @input_maker_label('Longitude')
      @input_maker_create('long', ['type' => 'string'],$station)
    </div>
    <div class="raw-margin-top-24">
      @input_maker_label('Spam')
      @input_maker_create('spam', [
          'type' => 'relationship',
          'model' => 'App\Models\Spam',
          'label' => 'name',
          'value' => 'id'
          ], $station)
    </div>
    <div class="raw-margin-top-24">
      @input_maker_label('Zona')
      @input_maker_create('zona', [
          'type' => 'relationship',
          'model' => 'App\Models\Zona',
          'label' => 'name',
          'value' => 'id'
          ],$station)
    </div>
    <div class="raw-margin-top-24">
      @input_maker_label('Dma')
      @input_maker_create('dma', [
          'type' => 'relationship',
          'model' => 'App\Models\Dma',
          'label' => 'name',
          'value' => 'id'
          ],$station)
    </div>
    <input type="hidden" name="id" value="{{ $station->v_spam_kode_id }}">
    <div class="raw-margin-top-24">
      @input_maker_label('Kode')
      @input_maker_create('kode', ['type' => 'string'],$station)      
    </div>
    <div class="raw-margin-top-24">
      @input_maker_label('Chart Url')
      @input_maker_create('chart_url', ['type' => 'string'],$station)
    </div>
    <div class="raw-margin-top-24">
      @input_maker_label('Data Url')
      @input_maker_create('data_url',['type' => 'string'],$station)
    </div>
    <br>
        <div class="form-group">
          <label class="control-label">Tanggal Instalasi</label>
          <input type="text" class="form-control" name="instalation_date" value="" id="instalation_date">
        </div>
        <div class="raw-margin-top-24">
          <a class="btn btn-default pull-left" href="{!! route('stations.index') !!}">Batal</a>
          <button class="btn btn-primary pull-right" type="submit">Simpan</button>
        </div>

        {!! Form::close() !!}
      </div>
  </div>

  <div class="col-md-6 raw-margin-bottom-24">
            <div class="form-group">
                  <label class="control-label" for="avatar">Peta Area</label><br />(Drag marker untuk mengatur input koordinat)
                  <div style="width: 300px; height: 300px; border:1px solid #ccc;">
                    {!! Mapper::render() !!}
                  </div>
                </div>
       </div>
      </div> 

  @stop

resources/views/stations/index.blade.php
@extends('dashboard')

@section('content')

<div class="row">
    <div class="col-md-12" style="background:#eee; border-radius:0 0 14px 14px; margin:4px;">
        {!! Form::open(['route' => 'stations.search','class' => 'pull-right raw-margin-top-24 raw-margin-left-24']) !!}
        {!! csrf_field() !!}
        <input class="form-control form-inline pull-right" name="search" placeholder="Search">
        {!! Form::close() !!}
        <a class="btn btn-primary pull-right" style="margin-top: 25px" href="{!! route('stations.create') !!}">Tambah Baru</a>
        <h1 class="pull-left"><span class="fa fa-tachometer"></span> Kelola Logger</h1>
    </div>
</div>
<div class="row raw-margin-top-24">
    <div class="col-md-12">
        @if($stations->isEmpty())
        <div class="well text-center">Logger Tidak Ditemukan.</div>
        @else
        <table class="table table-striped">
            <thead>
                <th>Nama</th>
                <th width="140px" class="text-right">Aksi</th>
            </thead>
            <tbody>
                @foreach($stations as $station)
                <tr>
                    <td>
                        {{ $station->name }}
                    </td>
                    <td>
                        <form method="post" action="{!! route('stations.destroy', [$station->id]) !!}">
                            {!! csrf_field() !!}
                            {!! method_field('DELETE') !!}
                            <button class="btn btn-danger btn-xs pull-right" type="submit" onclick="return confirm('Are you sure you want to delete this station?')"><i class="fa fa-trash"></i> Hapus</button>
                        </form>
                        <!-- {{-- <a class="btn btn-warning btn-xs" href="{!! route('stations.show', [$station->id]) !!}"><i class="fa fa-search"></i> Show</a> --}} -->
                        <a class="btn btn-warning btn-xs" href="{!! route('stations.edit', [$station->id]) !!}"><i class="fa fa-pencil"></i> Ubah</a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <div class="row text-center">
            {!! $stations; !!}
        </div>
        @endif
    </div>
</div>

@stop

resources/views/stations/show.blade.php
@extends('dashboard')

@section('content')

    <div class="row">
        <div class="col-md-12">
        <h1>{{ $station->name }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
        Modify this page for detailed show/info.
        </div>
    </div>
    {!! link_to(URL::previous(), 'Back', ['class' => 'btn btn-default btn-primary pull-right']) !!}
@stop