routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Non protected/public routes
Route::get('/', 'WelcomeController@index');
Route::get('pdashboard', 'DashboardController@index');
Route::get('pdashboard/detail', 'DashboardController@detail');
Route::get('pdashboard/detail_nrw', 'DashboardController@detail_nrw');
// Login Logout
Route::get('login', 'Auth\LoginController@showLoginForm');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout');
// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
// Regisration
Route::get('register', 'Auth\RegisterController@showRegistrationForm');
Route::post('register', 'Auth\RegisterController@register');
Route::get('activate', 'Auth\ActivateController@showActivate');
Route::get('activate/send-token', 'Auth\ActivateController@sendToken');
Route::get('activate/token/{token}', 'Auth\ActivateController@activate');

// HARUS login / Authenticated Routes
Route::group(['middleware' => ['auth', 'active']], function () {
    // User stuff
    Route::get('/users/switch-back', 'Admin\UserController@switchUserBack');
    Route::group(['prefix' => 'user', 'namespace' => 'User'], function () {
        Route::get('settings', 'SettingsController@settings');
        Route::post('settings', 'SettingsController@update');
        Route::post('editmeta/{id}', 'SettingsController@updatemeta');
        Route::get('password', 'PasswordController@password');
        Route::post('password', 'PasswordController@update');
    });
    // Dashboard
    Route::get('/dashboard', 'PagesController@dashboard');

    // Team
    Route::get('team/{name}', 'TeamController@showByName');
    Route::resource('teams', 'TeamController', ['except' => ['show']]);
    Route::post('teams/search', 'TeamController@search');
    Route::post('teams/{id}/invite', 'TeamController@inviteMember');
    Route::get('teams/{id}/remove/{userId}', 'TeamController@removeMember');


    // HARUS login, HARUS admin atau member
    Route::group(['middleware' => 'roles:admin|member'], function () {
        Route::resource('contents', 'ContentsController');
        Route::post('contents/search', [
            'as' => 'contents.search',
            'uses' => 'ContentsController@search'
        ]);
    });

    // HARUS login, HARUS admin
    Route::group(['middleware' => 'roles:admin'], function () {
      // Organization & References
      Route::resource('companies', 'CompaniesController');
      Route::post('companies/search', [
          'as' => 'companies.search',
          'uses' => 'CompaniesController@search'
      ]);

      // CMS
      Route::resource('topics', 'TopicsController');
      Route::post('topics/search', [
          'as' => 'topics.search',
          'uses' => 'TopicsController@search'
      ]);
      Route::resource('categories', 'CategoriesController');
      Route::post('categories/search', [
          'as' => 'categories.search',
          'uses' => 'CategoriesController@search'
      ]);
      Route::resource('offlinewriters', 'OfflineWritersController');
      Route::post('offlinewriters/search', [
          'as' => 'offlinewriters.search',
          'uses' => 'OfflineWritersController@search'
      ]);
      Route::resource('comments', 'CommentsController');
      Route::post('comments/search', [
          'as' => 'comments.search',
          'uses' => 'CommentsController@search'
      ]);
      // Log System
      Route::resource('logsystems', 'LogsystemsController');
      Route::post('logsystems/search', [
          'as' => 'logsystems.search',
          'uses' => 'LogsystemsController@search'
      ]);
      // Spams
      Route::resource('spams', 'SpamsController');
      Route::post('spams/search', [
          'as' => 'spams.search',
          'uses' => 'SpamsController@search'
      ]);

      // Dma
      Route::resource('dmas', 'DmasController');
      Route::post('dmas/search', [
      'as' => 'dmas.search',
      'uses' => 'DmasController@search'
      ]);
      Route::post('dmas/assign', [
      'as' => 'dmas.assign',
      'uses' => 'DmasController@assign'
      ]);

      // Zona
      Route::resource('zonas', 'ZonasController');
      Route::post('zonas/search', [
          'as' => 'zonas.search',
          'uses' => 'ZonasController@search'
      ]);

      // Brand
      Route::resource('brands', 'BrandsController');
      Route::post('brands/search', [
          'as' => 'brands.search',
          'uses' => 'BrandsController@search'
      ]);
      // Location
      Route::resource('locations', 'LocationsController');
      Route::post('locations/search', [
          'as' => 'locations.search',
          'uses' => 'LocationsController@search'
      ]);

      // Station
      Route::resource('stations', 'StationsController');
      Route::post('stations/search', [
          'as' => 'stations.search',
          'uses' => 'StationsController@search'
      ]);

      // Device
      Route::resource('devices', 'DevicesController');
      Route::post('devices/search', [
          'as' => 'devices.search',
          'uses' => 'DevicesController@search'
      ]);

      // Grafik & Statistik
      Route::get('waterbalance', [
          'as' => 'nrws.waterbalance',
          'uses' => 'NrwsController@waterbalance'
      ]);
      Route::get('chartmeasurement', [
          'as' => 'nrws.chartmeasurement',
          'uses' => 'NrwsController@chartmeasurement'
      ]);


    });

    // HARUS login, HARUS admin dan controllernya HARUS di /admin
    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
        // User
        Route::resource('users', 'UserController', ['except' => ['create', 'show']]);
        Route::post('users/search', 'UserController@search');
        Route::get('users/search', 'UserController@index');
        Route::get('users/invite', 'UserController@getInvite');
        Route::get('users/switch/{id}', 'UserController@switchToUser');
        Route::post('users/invite', 'UserController@postInvite');
        // Roles
        Route::resource('roles', 'RoleController', ['except' => ['show']]);
        Route::post('roles/search', 'RoleController@search');
        Route::get('roles/search', 'RoleController@index');
    });
});

app/Models/Dma.php
<?php

namespace App\Models;

use App\Models\Pelanggan;
use App\Models\Zona;
use Illuminate\Database\Eloquent\Model;
use App\Models\Station;

class Dma extends Model
{
    public $table = "dmas";

    public $primaryKey = "id";

    public $timestamps = true;

    public $fillable = [
        'id',
        'zona_id',
        'kode',
        'name',
        'station',
        'polygon',
        'lat',
        'long'
    ];

    public static $rules = [
        // create rules
        // 'zona_id' => 'required',
        // 'kode' => 'required|string:2',
        // 'name' => 'required',
    ];

    // Dma
    public function pelanggans()
    {
        return $this->belongsToMany(Pelanggan::class, 'pelanggan_dmas',
            'dma_id', 'pel_no');
    }

    public function zona()
    {
        return $this->belongsTo(Zona::class);
    } 
  
    public function stations()
    {
        return $this->hasMany(Station::class,'station');
    }
}

app/Http/Controllers/DmasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\DmaService;
use App\Http\Requests\DmaCreateRequest;
use App\Http\Requests\DmaUpdateRequest;
use Mapper;
use App\Models\Pelanggan;
use App\Models\PelangganDkd;

class DmasController extends Controller
{
    public function __construct(DmaService $dmaService)
    {
        $this->service = $dmaService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $dmas = $this->service->paginated();
        return view('dmas.index')->with('dmas', $dmas);
    }

    /**
     * Display a listing of the resource searched.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $dmas = $this->service->search($request->search);
        return view('dmas.index')->with('dmas', $dmas);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        return view('dmas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\DmaCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DmaCreateRequest $request)
    {
        $result = $this->service->create($request->except('_token'));

        if ($result) {
            return redirect(route('dmas.index'))->with('message', 'Successfully created');
            //return redirect(route('dmas.edit', ['id' => $result->id]))->with('message', 'Successfully created');
        }

        return redirect(route('dmas.index'))->with('message', 'Failed to create');
    }

    // Digunakan untuk manajemen pelanggan-DMA
    public function show($id, Request $request)
    {
        $dma = $this->service->find($id);
        if ($dma->lat != null) {
          Mapper::map($dma->lat,$dma->long, [
          'draggable' => false,
          ]);
        } else {
          Mapper::map(-6.9809279,107.486755, [
          'draggable' => false,
          ]);
        }

        // Kalau belum milih DKD, siapkan dropdown DKD
        // Sementara dari groupby tm_pelanggan (banyak row bgt), nanti dicari sumber dkd yg lebih friendly
        if($request->dkd_id == null) {

          $dkds = PelangganDkd::select('dkd_kd')->groupBy('dkd_kd')->orderBy('dkd_kd','DESC')->get();
          $dkd_id = null;
          return view('dmas.show', compact('dma','dkd_id','dkds'));

        } else {

          $dkd_id = $request->dkd_id;
          $pelanggans = Pelanggan::where('dkd_kd','=',$dkd_id)->get();
          $memberdmas = $dma->pelanggans()->get();

          return view('dmas.show', compact('dma','pelanggans','memberdmas','dkd_id'));

        }



    }

    /**
     * Show the form for editing the dma.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dma = $this->service->find($id);
        if ($dma->lat != null) {
        Mapper::map(-6.849464713343289, 107.58418970979005)->polygon([ ['latitude' => -6.7975804862857885, 'longitude' => 107.53203392028809],
            ['latitude' => -6.799114575998445, 'longitude' => 107.55795478820801],
            ['latitude' => -6.802353193752624, 'longitude' => 107.57357597351074],
            ['latitude' => -6.827068240877113, 'longitude' => 107.57306098937988],
            ['latitude' => -6.836272139404449, 'longitude' => 107.53237724304199],
            ['latitude' => -6.81854595477611, 'longitude' => 107.51143455505371]],
            ['strokeColor' => '#500000', 'strokeOpacity' => 0.1, 'strokeWeight' => 2, 'fillColor' => '#FFFFFF']);
      } else {
        Mapper::map(-6.849464713343289, 107.58418970979005)->polygon([ ['latitude' => -6.7975804862857885, 'longitude' => 107.53203392028809],
            ['latitude' => -6.799114575998445, 'longitude' => 107.55795478820801],
            ['latitude' => -6.802353193752624, 'longitude' => 107.57357597351074],
            ['latitude' => -6.827068240877113, 'longitude' => 107.57306098937988],
            ['latitude' => -6.836272139404449, 'longitude' => 107.53237724304199],
            ['latitude' => -6.81854595477611, 'longitude' => 107.51143455505371]],
            ['strokeColor' => '#500000', 'strokeOpacity' => 0.3, 'strokeWeight' => 2, 'fillColor' => '#FFFFFF']);
      }

        $dma = $this->service->find($id);
        return view('dmas.edit')->with('dma', $dma);
    }

    /**
     * Update the dmas in storage.
     *
     * @param  \Illuminate\Http\DmaUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(DmaUpdateRequest $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
            //return back()->with('message', 'Successfully updated');
            return redirect(route('dmas.index'))->with('message', 'Successfully updated');
        }

        return back()->with('message', 'Failed to update');
    }

    public function assign(Request $request)
    {

        $dma = $this->service->find($request->dma_id);

        $memberdmas = $request->input('search_to');
        //$memberdmas = implode(',', $memberdmas);
        $result = $dma->pelanggans()->detach();
        $result = $dma->pelanggans()->attach($memberdmas);

        //return back()->with('message', 'Failed to update');
        return back()->with('message', 'Successfully updated');
    }

    /**
     * Remove the dmas from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->service->destroy($id);

        if ($result) {
            return redirect(route('dmas.index'))->with('message', 'Successfully deleted');
        }

        return redirect(route('dmas.index'))->with('message', 'Failed to delete');
    }

}

resources/views/dmas/create.blade.php
@extends('dashboard')

@section('content')
<header>
 <script src="https://maps.googleapis.com/maps/api/js?libraries=geometry,drawing"></script>
 <script>
     var geocoder;
     var map;
     var polygonArray = [];
     function initialize() {
      map = new google.maps.Map(
       document.getElementById("map_canvas"), {
        center: new google.maps.LatLng(-6.956273, 107.546515),
        zoom: 9,
        mapTypeId: google.maps.MapTypeId.ROADMAP
    });
      var drawingManager = new google.maps.drawing.DrawingManager({
        drawingMode: google.maps.drawing.OverlayType.POLYGON,
        drawingControl: true,
        drawingControlOptions: {
         position: google.maps.ControlPosition.TOP_CENTER,
         drawingModes: [
         google.maps.drawing.OverlayType.POLYGON,
         ]
     },
     polygonOptions: {
        fillColor: '#BCDCF9',
        fillOpacity: 0.5,
        strokeWeight: 2,
        strokeColor: '#57ACF9',
        clickable: false,
        editable: false,
        zIndex: 1
    }
});
      console.log(drawingManager)
      drawingManager.setMap(map)
      google.maps.event.addListener(drawingManager, 'polygoncomplete', function(polygon) {
        var dat;
        for (var i = 0; i < polygon.getPath().getLength(); i++) {
         dat += polygon.getPath().getAt(i).toUrlValue(6) + ";";
     }
     document.getElementById('polygon').value=dat.replace('undefined','');
     polygonArray.push(polygon);
 });

  }
  google.maps.event.addDomListener(window, "load", initialize);
</script>
</header>
<div class="row">
    <div class="col-md-12" style="background:#eee; border-radius:0 0 14px 14px; margin:4px;">
        <h1 class="pull-left"><span class="fa fa-map-marker"></span> Tambah DMA</h1>
    </div>
</div>

<div class="row raw-margin-top-24">
    <div class="col-md-6 raw-margin-bottom-24">
        {!! Form::open(['route' => 'dmas.store']) !!}
        {!! csrf_field() !!}

        @form_maker_table("dmas",[
            'id'=> ['type'=>'hidden'],
            'zona_id'=>['alt_name'=>'Zona','type'=>'relationship','model' =>
            'App\Models\Zona','method'=>'nama_kode'],
            'kode' => ['alt_name'=>'Kode'],
            'name' => ['alt_name'=>'Nama'],
            ])

            <div class="form-group polygon">
                <label for="polygon">Polygon</label>
                <input class="form-control" type="text" name="polygon" id="polygon" required placeholder="Polygon">
            </div>
            <div id="map_canvas" style=" border: 2px solid #3872ac;">
            </div>

            <div class="raw-margin-top-24">
                <a class="btn btn-default pull-left" href="{!! route('dmas.index') !!}">Batal</a>
                <button class="btn btn-primary pull-right" type="submit">Buat</button>

                {!! Form::close() !!}
            </div>

        </div>
    </div>

    @stop

resources/views/dmas/edit.blade.php
@extends('dashboard')

@section('content')

<div class="row">
  <div class="col-md-12" style="background:#eee; border-radius:0 0 14px 14px; margin:4px;">
    <h1 class="pull-left"><span class="fa fa-map-marker"></span> Ubah DMA</h1>
  </div>
</div>
<div class="row raw-margin-top-24">
  <div class="col-md-6 raw-margin-bottom-24">
    <div>
      {!! Form::model($dma, ['route' => ['dmas.update', $dma->id], 'method' => 'patch']) !!}
      {!! csrf_field() !!}
      {!! method_field('PATCH') !!}

      {!! Form::open(['route' => 'dmas.store']) !!}
      {!! csrf_field() !!}

      @form_maker_object($dma, [
        'id'=> ['type'=>'hidden'],
        'zona'=>['alt_name'=>'Zona','type'=>'relationship','model' =>
        'App\Models\Zona','method'=>'nama_kode'],
        'kode' => ['alt_name'=>'Kode'],
        'name' => ['alt_name'=>'Nama'],
        'polygon' => ['type'=>'hidden'],
        'lat'=>['alt_name'=>'Latitude'],
        'long'=>['alt_name'=>'Longitude'],
        ])

        <div class="form-group">
          <label class="control-label" for="avatar">Peta Area</label><br />(Drag marker untuk mengatur input koordinat)
          <div style="width: 300px; height: 300px; border:1px solid #ccc;">
            {!! Mapper::render() !!}
          </div>
        </div>

        <div class="raw-margin-top-24">
          <a class="btn btn-default pull-left" href="{!! route('dmas.index') !!}">Batal</a>
          <button class="btn btn-primary pull-right" type="submit">Simpan</button>
        </div>
        {!! Form::close() !!}
      </div>
    </div>
  </div>

  @stop

resources/views/dmas/index.blade.php
@extends('dashboard')

@section('content')

    <div class="row">
        <div class="col-md-12" style="background:#eee; border-radius:0 0 14px 14px; margin:4px;">
            {!! Form::open(['route' => 'dmas.search','class' => 'pull-right raw-margin-top-24 raw-margin-left-24']) !!}
              {!! csrf_field() !!}
              <input class="form-control form-inline pull-right" name="search" placeholder="Search">
            {!! Form::close() !!}
            <a class="btn btn-primary pull-right" style="margin-top: 25px" href="{!! route('dmas.create') !!}">Tambah Baru</a>
            <h1 class="pull-left"><span class="fa fa-map-marker"></span> Kelola DMA</h1>
        </div>
    </div>
    <div class="row raw-margin-top-24">
        <div class="col-md-12">
            @if($dmas->isEmpty())
                <div class="well text-center">DMA Tidak Di Temukan.</div>
            @else
                <table class="table table-striped">
                    <thead>
                        <th>Nama District Metering Area</th>
                        <th>Kode</th>
                        <th width="350px" class="text-right">Aksi</th>
                    </thead>
                    <tbody>
                    @foreach($dmas as $dma)
                        <tr>
                            <td>
                                {{ $dma->name }}
                            </td>

                            <td>
                                {{ $dma->kode }}
                            </td>

                            <td>
                                <a style="margin:1px;" class="btn btn-primary btn-xs pull-right" href="{!! route('dmas.show', [$dma->id]) !!}"><i class="fa fa-plug"></i> Kelola Pelanggan+DMA</a>
                                <a style="margin:1px;" class="btn btn-warning btn-xs pull-right" href="{!! route('dmas.edit', [$dma->id]) !!}"><i class="fa fa-pencil"></i> Ubah</a>
                                <form method="post" action="{!! route('dmas.destroy', [$dma->id]) !!}">
                                    {!! csrf_field() !!}
                                    {!! method_field('DELETE') !!}
                                    <button style="margin:1px;" class="btn btn-danger btn-xs pull-right" type="submit" onclick="return confirm('Are you sure you want to delete this dma?')"><i class="fa fa-trash"></i> Hapus</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

                <div class="row text-center">
                    {!! $dmas; !!}
                </div>
            @endif
        </div>
    </div>

@stop

resources/views/dmas/show.blade.php
@extends('dashboard')

@section('javascript')
<script src="{{ url('js/multiselect.min.js') }}"></script>
<script type="text/javascript">
jQuery(document).ready(function($) {
   $('#search').multiselect({
        search: {
            left: '<input type="text" name="q" class="form-control" placeholder="Search..." />',
            right: '<input type="text" name="q" class="form-control" placeholder="Search..." />',
           },
        fireSearch: function(value) {
            return value.length > 3;
       }
    });
});
</script>

@stop

@section('content')

    <div class="row">
        <div class="col-md-12" style="background:#eee; border-radius:0 0 14px 14px; margin:4px;">
        <h1 class="pull-left"><span class="fa fa-map-marker"></span> Pengelolaan Pelanggan ke DMA</h1>
        </div>
    </div>

    @if($dkd_id)

      <div class="row raw-margin-top-24">
          <div class="col-md-12">
          <div style="width: 300px; height: 200px; border:1px solid #ccc; float:left; margin-right:14px;">
            {!! Mapper::render() !!}
          </div>
          <p><b>Nama DMA:</b> {{ $dma->name }}</p>
          <p><b>Kode DMA:</b> {{ $dma->kode }}</p>
          <p><b>Zona:</b> {{ $dma->zona->name }}</p>
          <p><b>SPAM:</b> {{ $dma->zona->spam->name }}</p>
          <p><b>DKD Saat Ini:</b> {{ $dkd_id }}</p>
          </div>
      </div>

      <br />

      {!! Form::open(['route' => 'dmas.assign']) !!}
      {!! csrf_field() !!}
      <div class="row">
      <div class="col-xs-5">
          <span style="font-weight:bold;">Pelanggan</span>
          <select name="from[]" id="search" class="form-control" size="12" multiple="multiple">
            @foreach($pelanggans as $pelanggan)
              <option value="{{ $pelanggan->pel_no }}">{{ (string) $pelanggan->pel_no }} {{ $pelanggan->pel_nama }}</option>
            @endforeach
          </select>
      </div>

      <div class="col-xs-2">
          <br /><br />
          <button type="button" id="search_rightAll" class="btn btn-block"><i class="fa fa-forward"></i></button>
          <button type="button" id="search_rightSelected" class="btn btn-block"><i class="fa fa-chevron-right"></i></button>
          <button type="button" id="search_leftSelected" class="btn btn-block"><i class="fa fa-chevron-left"></i></button>
          <button type="button" id="search_leftAll" class="btn btn-block"><i class="fa fa-backward"></i></button>
      </div>

      <div class="col-xs-5">
          <span style="font-weight:bold;">Anggota DMA</span>
          <select name="search_to[]" id="search_to" class="form-control" size="12" multiple="multiple">
            @foreach($memberdmas as $memberdma)
              <option value="{{ $memberdma->pel_no }}">{{ (string) $memberdma->pel_no }} {{ $memberdma->pel_nama }}</option>
            @endforeach
          </select>
      </div>
      </div>

      <input type="hidden" name="dma_id" value="{{ $dma->id }}" />

      <br />
      {!! link_to(URL::previous(), 'Back', ['class' => 'btn btn-default pull-left']) !!}
      &nbsp;
      <button class="btn btn-primary" type="submit">Update / Assign</button>
      {!! Form::close() !!}

    @else

    <div class="row raw-margin-top-24">
        <div class="col-md-6">

        <h3>Pilih DKD yang akan dikelola pelanggannya (ke DMA) terlebih dahulu.</h3>

        {!! Form::open(['url' => 'dmas/'.$dma->id, 'method' => 'get' ]) !!}
        {!! csrf_field() !!}
        <input type="hidden" name="dma" value="{{$dma->id}}">
        <label class="control-label" for="dkd_id">DKD :</label><br />
        <select class="form-control" name="dkd_id" id="dkd_id">
          @foreach ($dkds as $dkd)
            <option value="{{$dkd->dkd_kd}}">{{$dkd->dkd_kd}}</option>
          @endforeach
        </select>
        <br />
        <button class="btn btn-primary" type="submit">Lanjut</button>
        {!! Form::close() !!}

        </div>
    </div>

    <br />

    @endif



@stop