routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Non protected/public routes
Route::get('/', 'WelcomeController@index');
Route::get('pdashboard', 'DashboardController@index');
Route::get('pdashboard/detail', 'DashboardController@detail');
Route::get('pdashboard/detail_nrw', 'DashboardController@detail_nrw');
// Login Logout
Route::get('login', 'Auth\LoginController@showLoginForm');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout');
// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
// Regisration
Route::get('register', 'Auth\RegisterController@showRegistrationForm');
Route::post('register', 'Auth\RegisterController@register');
Route::get('activate', 'Auth\ActivateController@showActivate');
Route::get('activate/send-token', 'Auth\ActivateController@sendToken');
Route::get('activate/token/{token}', 'Auth\ActivateController@activate');

// HARUS login / Authenticated Routes
Route::group(['middleware' => ['auth', 'active']], function () {
    // User stuff
    Route::get('/users/switch-back', 'Admin\UserController@switchUserBack');
    Route::group(['prefix' => 'user', 'namespace' => 'User'], function () {
        Route::get('settings', 'SettingsController@settings');
        Route::post('settings', 'SettingsController@update');
        Route::post('editmeta/{id}', 'SettingsController@updatemeta');
        Route::get('password', 'PasswordController@password');
        Route::post('password', 'PasswordController@update');
    });
    // Dashboard
    Route::get('/dashboard', 'PagesController@dashboard');

    // Team
    Route::get('team/{name}', 'TeamController@showByName');
    Route::resource('teams', 'TeamController', ['except' => ['show']]);
    Route::post('teams/search', 'TeamController@search');
    Route::post('teams/{id}/invite', 'TeamController@inviteMember');
    Route::get('teams/{id}/remove/{userId}', 'TeamController@removeMember');


    // HARUS login, HARUS admin atau member
    Route::group(['middleware' => 'roles:admin|member'], function () {
        Route::resource('contents', 'ContentsController');
        Route::post('contents/search', [
            'as' => 'contents.search',
            'uses' => 'ContentsController@search'
        ]);
    });

    // HARUS login, HARUS admin
    Route::group(['middleware' => 'roles:admin'], function () {
      // Organization & References
      Route::resource('companies', 'CompaniesController');
      Route::post('companies/search', [
          'as' => 'companies.search',
          'uses' => 'CompaniesController@search'
      ]);

      // CMS
      Route::resource('topics', 'TopicsController');
      Route::post('topics/search', [
          'as' => 'topics.search',
          'uses' => 'TopicsController@search'
      ]);
      Route::resource('categories', 'CategoriesController');
      Route::post('categories/search', [
          'as' => 'categories.search',
          'uses' => 'CategoriesController@search'
      ]);
      Route::resource('offlinewriters', 'OfflineWritersController');
      Route::post('offlinewriters/search', [
          'as' => 'offlinewriters.search',
          'uses' => 'OfflineWritersController@search'
      ]);
      Route::resource('comments', 'CommentsController');
      Route::post('comments/search', [
          'as' => 'comments.search',
          'uses' => 'CommentsController@search'
      ]);
      // Log System
      Route::resource('logsystems', 'LogsystemsController');
      Route::post('logsystems/search', [
          'as' => 'logsystems.search',
          'uses' => 'LogsystemsController@search'
      ]);
      // Spams
      Route::resource('spams', 'SpamsController');
      Route::post('spams/search', [
          'as' => 'spams.search',
          'uses' => 'SpamsController@search'
      ]);

      // Dma
      Route::resource('dmas', 'DmasController');
      Route::post('dmas/search', [
      'as' => 'dmas.search',
      'uses' => 'DmasController@search'
      ]);
      Route::post('dmas/assign', [
      'as' => 'dmas.assign',
      'uses' => 'DmasController@assign'
      ]);

      // Zona
      Route::resource('zonas', 'ZonasController');
      Route::post('zonas/search', [
          'as' => 'zonas.search',
          'uses' => 'ZonasController@search'
      ]);

      // Brand
      Route::resource('brands', 'BrandsController');
      Route::post('brands/search', [
          'as' => 'brands.search',
          'uses' => 'BrandsController@search'
      ]);
      // Location
      Route::resource('locations', 'LocationsController');
      Route::post('locations/search', [
          'as' => 'locations.search',
          'uses' => 'LocationsController@search'
      ]);

      // Station
      Route::resource('stations', 'StationsController');
      Route::post('stations/search', [
          'as' => 'stations.search',
          'uses' => 'StationsController@search'
      ]);

      // Device
      Route::resource('devices', 'DevicesController');
      Route::post('devices/search', [
          'as' => 'devices.search',
          'uses' => 'DevicesController@search'
      ]);

      // Grafik & Statistik
      Route::get('waterbalance', [
          'as' => 'nrws.waterbalance',
          'uses' => 'NrwsController@waterbalance'
      ]);
      Route::get('chartmeasurement', [
          'as' => 'nrws.chartmeasurement',
          'uses' => 'NrwsController@chartmeasurement'
      ]);


    });

    // HARUS login, HARUS admin dan controllernya HARUS di /admin
    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
        // User
        Route::resource('users', 'UserController', ['except' => ['create', 'show']]);
        Route::post('users/search', 'UserController@search');
        Route::get('users/search', 'UserController@index');
        Route::get('users/invite', 'UserController@getInvite');
        Route::get('users/switch/{id}', 'UserController@switchToUser');
        Route::post('users/invite', 'UserController@postInvite');
        // Roles
        Route::resource('roles', 'RoleController', ['except' => ['show']]);
        Route::post('roles/search', 'RoleController@search');
        Route::get('roles/search', 'RoleController@index');
    });
});

app/Models/Spam.php
<?php

namespace App\Models;
use DB;
use App\Models\Zona;
use Illuminate\Database\Eloquent\Model;
use App\Models\Station;


class Spam extends Model
{
    public $table = "spams";

    public $primaryKey = "id";

    public $timestamps = true;

    public $fillable = [
        'id',
        'kode',
        'name',
        'polygon',
    ];

    public static $rules = [
        // create rules
        'kode'=>'required',
        'name'=>'required'
    ];

    public function kode_name()
    {
        return $this->select('name', DB::raw("CONCAT(`kode`, ' - ', `name`) AS name"),'id')->get();
    }

    public function zonas()
    {
        return $this->hasMany(Zona::class);
    }
    // 
    public function stations()
    {
        return $this->hasMany(Station::class);
    }
}

app/Http/Controllers/SpamsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\SpamService;
use App\Http\Requests\SpamCreateRequest;
use App\Http\Requests\SpamUpdateRequest;
use Mapper;

class SpamsController extends Controller
{
    public function __construct(SpamService $spamService)
    {
        $this->service = $spamService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $spams = $this->service->paginated();
        return view('spams.index')->with('spams', $spams);
    }

    /**
     * Display a listing of the resource searched.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $spams = $this->service->search($request->search);
        return view('spams.index')->with('spams', $spams);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    //   Mapper::map(-6.9809279,107.486755, [
    //     'draggable' => true,
    //     'eventDragEnd' =>
    //     'document.getElementById("Lat").value=event.latLng.lat();
    //     document.getElementById("Long").value=event.latLng.lng();'
    // ]);

        Mapper::map(-6.9809279,107.486755)->polygon([['latitude' => -6.9809279, 'longitude' => 107.486755], ['latitude' => 107.486760, 'longitude' => 107.486770]], ['strokeColor' => '#000000', 'strokeOpacity' => 0.1, 'strokeWeight' => 2, 'fillColor' => '#FFFFFF']);
        Mapper::polygon([['latitude' => -6.9809279, 'longitude' => 107.486755], ['latitude' => -6.9809280, 'longitude' => 107.486775]], ['editable' => 'true']);
        
      return view('spams.create');
  }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\SpamCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SpamCreateRequest $request)
    {
        $result = $this->service->create($request->except('_token'));

        if ($result) {
            return redirect(route('spams.index'))->with('message', 'Successfully created');
            //return redirect(route('spams.edit', ['id' => $result->id]))->with('message', 'Successfully created');
        }

        return redirect(route('spams.index'))->with('message', 'Failed to create');
    }

    /**
     * Display the spam.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $spam = $this->service->find($id);
        return view('spams.show')->with('spam', $spam);
    }

    /**
     * Show the form for editing the spam.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $spam = $this->service->find($id);
        if ($spam->lat != null) {
          /*
          Mapper::map($spam->lat,$spam->long, [
            'draggable' => true,
            'eventDragEnd' =>
            'document.getElementById("Lat").value=event.latLng.lat();
             document.getElementById("Long").value=event.latLng.lng();'
          ]);
          */
        //   $data_polygon = array(
        //     ['latitude' => -6.7975804862857885, 'longitude' => 107.53203392028809], 
        //     ['latitude' => -6.799114575998445, 'longitude' => 107.55795478820801],
        //     ['latitude' => -6.802353193752624, 'longitude' => 107.57357597351074], 
        //     ['latitude' => -6.827068240877113, 'longitude' => 107.57306098937988],
        //     ['latitude' => -6.836272139404449, 'longitude' => 107.53237724304199], 
        //     ['latitude' => -6.81854595477611, 'longitude' => 107.51143455505371]
        // );
          Mapper::map(-6.849464713343289, 107.58418970979005)->polygon([ ['latitude' => -6.7975804862857885, 'longitude' => 107.53203392028809], 
            ['latitude' => -6.799114575998445, 'longitude' => 107.55795478820801],
            ['latitude' => -6.802353193752624, 'longitude' => 107.57357597351074], 
            ['latitude' => -6.827068240877113, 'longitude' => 107.57306098937988],
            ['latitude' => -6.836272139404449, 'longitude' => 107.53237724304199], 
            ['latitude' => -6.81854595477611, 'longitude' => 107.51143455505371]],
            ['strokeColor' => '#000000', 'strokeOpacity' => 0.3, 'strokeWeight' => 2, 'fillColor' => '#FFFFFF']);
      } else {
          /*
          Mapper::map(-6.9809279,107.486755, [
            'draggable' => true,
            'eventDragEnd' =>
            'document.getElementById("Lat").value=event.latLng.lat();
             document.getElementById("Long").value=event.latLng.lng();'
          ]);
          */
        //   $data_polygon = array(
        //     ['latitude' => -6.7975804862857885, 'longitude' => 107.53203392028809], ['latitude' => -6.799114575998445, 'longitude' => 107.55795478820801],
        //     ['latitude' => -6.802353193752624, 'longitude' => 107.57357597351074], ['latitude' => -6.827068240877113, 'longitude' => 107.57306098937988],
        //     ['latitude' => -6.836272139404449, 'longitude' => 107.53237724304199], ['latitude' => -6.81854595477611, 'longitude' => 107.51143455505371]
        // );
          Mapper::map(-6.849464713343289, 107.58418970979005)->polygon([ ['latitude' => -6.7975804862857885, 'longitude' => 107.53203392028809], 
            ['latitude' => -6.799114575998445, 'longitude' => 107.55795478820801],
            ['latitude' => -6.802353193752624, 'longitude' => 107.57357597351074], 
            ['latitude' => -6.827068240877113, 'longitude' => 107.57306098937988],
            ['latitude' => -6.836272139404449, 'longitude' => 107.53237724304199], 
            ['latitude' => -6.81854595477611, 'longitude' => 107.51143455505371]],
            ['strokeColor' => '#000000', 'strokeOpacity' => 0.3, 'strokeWeight' => 2, 'fillColor' => '#FFFFFF']);

      }
      return view('spams.edit')->with('spam', $spam);
  }

    /**
     * Update the spams in storage.
     *
     * @param  \Illuminate\Http\SpamUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SpamUpdateRequest $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
            //return back()->with('message', 'Successfully updated');
            return redirect(route('spams.index'))->with('message', 'Successfully updated');
        }

        return back()->with('message', 'Failed to update');
    }

    /**
     * Remove the spams from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->service->destroy($id);

        if ($result) {
            return redirect(route('spams.index'))->with('message', 'Successfully deleted');
        }

        return redirect(route('spams.index'))->with('message', 'Failed to delete');
    }
}

resources/views/spams/create.blade.php
@extends('dashboard')

@section('content')
<header>
 <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBNeEuP2m5QWfpG5jANn3SS2Iq3m1a8AlM&libraries=geometry,drawing"></script>
 <script>
     var geocoder; 
     var map;
     var polygonArray = [];
     function initialize() {
      map = new google.maps.Map(
       document.getElementById("map_canvas"), {
        center: new google.maps.LatLng(-6.956273, 107.546515),
        zoom: 9,
        mapTypeId: google.maps.MapTypeId.ROADMAP
    });
      var drawingManager = new google.maps.drawing.DrawingManager({
        drawingMode: google.maps.drawing.OverlayType.POLYGON,
        drawingControl: true,
        drawingControlOptions: {
         position: google.maps.ControlPosition.TOP_CENTER,
         drawingModes: [
         google.maps.drawing.OverlayType.POLYGON,
         ]
     },
     polygonOptions: {
        fillColor: '#BCDCF9',
        fillOpacity: 0.5,
        strokeWeight: 2,
        strokeColor: '#57ACF9',
        clickable: false,
        editable: false,
        zIndex: 1
    }
});
      console.log(drawingManager)
      drawingManager.setMap(map)
      google.maps.event.addListener(drawingManager, 'polygoncomplete', function(polygon) {
        var dat;
        for (var i = 0; i < polygon.getPath().getLength(); i++) {
         dat += polygon.getPath().getAt(i).toUrlValue(6) + ";";
     }
     document.getElementById('polygon').value=dat.replace('undefined','');
     polygonArray.push(polygon);
 });

  }
  google.maps.event.addDomListener(window, "load", initialize);
</script>
</header>
<div class="row">
    <div class="col-md-12" style="width: 98.8%;background:#eee; border-radius:0 0 14px 14px; margin:4px;">
        <h1 class="pull-left"><span class="fa fa-map-o"></span> Tambah SPAM</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-6 raw-margin-bottom-24">

        {!! Form::open(['route' => 'spams.store']) !!}
        {!! csrf_field() !!}

        @form_maker_table("spams",[
            'id'=>['type'=>'hidden'],
            'polygon'=>['type'=>'hidden'],
            'kode'=>['alt_name'=>'Kode'],
            'name'=>['alt_name'=>'Nama'],
            ])

            <div class="form-group polygon">
                <label for="polygon">Polygon</label>
                <input class="form-control" type="text" name="polygon" id="polygon" required placeholder="Polygon">
            </div>
                <div id="map_canvas" style=" border: 2px solid #3872ac;">
            </div>

            <div class="raw-margin-top-24">
                <a class="btn btn-default pull-left" href="{!! route('spams.index') !!}">Batal</a>
                <button class="btn btn-primary pull-right" type="submit">Buat</button>
            </div>

            {!! Form::close() !!}
        </div>

    </div>
</div>

@stop

resources/views/spams/edit.blade.php
@extends('dashboard')

@section('content')

<header>
 <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBNeEuP2m5QWfpG5jANn3SS2Iq3m1a8AlM&libraries=geometry,drawing"></script>
 <script>
     var geocoder; 
     var map;
     var polygonArray = [];
     function initialize() {
      map = new google.maps.Map(
       document.getElementById("map_canvas"), {
        center: new google.maps.LatLng(-6.956273, 107.546515),
        zoom: 9,
        mapTypeId: google.maps.MapTypeId.ROADMAP
    });
      var drawingManager = new google.maps.drawing.DrawingManager({
        drawingMode: google.maps.drawing.OverlayType.POLYGON,
        drawingControl: true,
        drawingControlOptions: {
         position: google.maps.ControlPosition.TOP_CENTER,
         drawingModes: [
         google.maps.drawing.OverlayType.POLYGON,
         ]
     },
     polygonOptions: {
        fillColor: '#BCDCF9',
        fillOpacity: 0.5,
        strokeWeight: 2,
        strokeColor: '#57ACF9',
        clickable: false,
        editable: false,
        zIndex: 1
    }
});
      console.log(drawingManager)
      drawingManager.setMap(map)
      google.maps.event.addListener(drawingManager, 'polygoncomplete', function(polygon) {
        var dat;
        for (var i = 0; i < polygon.getPath().getLength(); i++) {
         dat += polygon.getPath().getAt(i).toUrlValue(6) + ";";
     }
     document.getElementById('polygon').value=dat.replace('undefined','');
     polygonArray.push(polygon);
 });

  }
  google.maps.event.addDomListener(window, "load", initialize);
</script>
</header>

<div class="row">
    <div class="col-md-12" style="width: 98.8%;background:#eee; border-radius:0 0 14px 14px; margin:4px;">
        <h1 class="pull-left"><span class="fa fa-map-o"></span> Ubah SPAM</h1>
    </div>
</div>
<br>
  <div class="row">
      <div class="col-md-6 raw-margin-bottom-24">
          <div>
              {!! Form::model($spam, ['route' => ['spams.update', $spam->id], 'method' => 'patch']) !!}
                  {!! csrf_field() !!}
                  {!! method_field('PATCH') !!}

                  {!! Form::open(['route' => 'spams.store']) !!}
                      {!! csrf_field() !!}

                      @form_maker_object( $spam ,[
                      'id'=>['type'=>'hidden'],
                      'kode'=>['alt_name'=>'Kode'],
                      'name'=>['alt_name'=>'Nama'],
                      ])

                  <div class="form-group polygon">
                    <label class="control-label" for="polygon">Peta Area Poligon</label>
                    <input class="form-control" value="{{ $spam->polygon }}" type="text" name="polygon" id="polygon" required placeholder="Polygon">
                    <br/>(Klik objek untuk mengatur input koordinat)

                    <div id="map_canvas" style=" border: 2px solid #3872ac;">
                      
                    </div>
                  </div>

                  <div class="raw-margin-top-24">
                      <a class="btn btn-default pull-left" href="{!! route('spams.index') !!}">Batal</a>
                      <button class="btn btn-primary pull-right" type="submit">Simpan</button>
                  </div>

            {!! Form::close() !!}
          </div>
      </div>
  </div>

@stop

resources/views/spams/index.blade.php
@extends('dashboard')

@section('content')
    <div class="row">
    <div class="col-md-12" style="width: 98.8%; background:#eee; border-radius:0 0 14px 14px; margin: 4px;">
        {!! Form::open(['route' => 'spams.search','class' => 'pull-right raw-margin-top-24 raw-margin-left-24']) !!}
          {!! csrf_field() !!}
          <input class="form-control form-inline pull-right" name="search" placeholder="Search">
        {!! Form::close() !!}
        <a class="btn btn-primary pull-right" style="margin-top: 25px" href="{!! route('spams.create') !!}">Tambah Baru</a>
        <h1 class="pull-left"><span class="fa fa-map-o"></span> Kelola SPAM</h1>
    </div>
</div>
    <div class="row raw-margin-top-24">
        <div class="col-md-12">
            @if($spams->isEmpty())
                <div class="well text-center">SPAM Tidak Ditemukan.</div>
            @else
                <table class="table table-striped">
                    <thead>
                        <th>Nama Sistem Penyediaan Air Minum</th>
                        <th>Kode</th>
                        <th width="140px" class="text-right">Aksi</th>
                    </thead>
                    <tbody>
                    @foreach($spams as $spam)
                        <tr>
                            <td>
                                {{ $spam->name }}
                            </td>

                            <td>
                                {{ $spam->kode }}
                            </td>
                            <td>
                                <form method="post" action="{!! route('spams.destroy', [$spam->id]) !!}">
                                    {!! csrf_field() !!}
                                    {!! method_field('DELETE') !!}
                                    <button class="btn btn-danger btn-xs pull-right" type="submit" onclick="return confirm('Are you sure you want to delete this spam?')"><i class="fa fa-trash"></i> Hapus</button>
                                </form>
                               {{--  <a class="btn btn-warning btn-xs" href="{!! route('spams.show', [$spam->id]) !!}"><i class="fa fa-search"></i> Show</a> --}}

                                <a class="btn btn-warning btn-xs" href="{!! route('spams.edit', [$spam->id]) !!}"><i class="fa fa-pencil"></i> Ubah</a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

                <div class="row text-center">
                    {!! $spams; !!}
                </div>
            @endif
        </div>
    </div>

@stop

resources/views/spams/show.blade.php
@extends('dashboard')

@section('content')

    <div class="row">
        <div class="col-md-12">
        <h1>{{ $spam->name }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
        Modify this page for detailed show/info.
        </div>
    </div>
    {!! link_to(URL::previous(), 'Back', ['class' => 'btn btn-default btn-primary pull-right']) !!}
@stop